using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyConfigurationAttribute("Debug")]
[assembly: AssemblyCompanyAttribute("Thermo Fisher Scientific Inc. ")]
[assembly: AssemblyProductAttribute("SampleManager")]
[assembly: AssemblyCopyrightAttribute("© Copyright Thermo Fisher Scientific Inc. 1985-2016. All rights reserved.")]
[assembly: AssemblyVersionAttribute("11.2.2.0")]
[assembly: AssemblyInformationalVersionAttribute("11.2.2.0")]
[assembly: AssemblyFileVersionAttribute("11.2.2.0")]